from enum import Enum, IntEnum, auto
from dataclasses import dataclass
from datetime import datetime

class AlarmSeverity(IntEnum):
    """Severity level of an alarm."""

    INFO = 10
    WARNING = 20
    ERROR = 30
    CRITICAL = 40

    def __str__(self) -> str:
        return self.name

class ComparisonOperator(Enum):
    LT = "<"
    LE = "<="
    EQ = "=="
    NE = "!="
    GE = ">="
    GT = ">"

    def __str__(self):
        return self.value

class InvalidValuePolicy(Enum):
    IGNORE = auto()
    ALARM = auto()

@dataclass 
class AlarmRule:
    """Base class for all alarm rules related devices measurements."""
    name: str
    var_name: str
    operator: ComparisonOperator
    threshold: float
    severity: AlarmSeverity
    enabled: bool = True
    invalid_policy: InvalidValuePolicy = InvalidValuePolicy.ALARM

    @classmethod
    def from_dict(cls, cfg: dict) -> "AlarmRule":

        required = (
            "name",
            "var_name",
            "operator",
            "threshold",
            "severity",
        )

        for key in required:
            if key not in cfg:
                raise RuntimeError(
                    f"Missing alarm configuration key '{key}'."
                )
        
        return cls(
            name=cfg["name"],
            var_name=cfg["var_name"],
            operator=ComparisonOperator(cfg["operator"]),
            threshold=cfg["threshold"],
            severity=AlarmSeverity[cfg["severity"].upper()],
            enabled=cfg.get("enabled", True),
            alarm_on_invalid=cfg.get("alarm_on_invalid", True),
        )

class AlarmEventType(Enum):
    ACTIVATED = auto()
    UPDATED = auto()
    SUPPRESSED = auto() #This tells the AlarmManager to remove the alarm without notification

@dataclass
class AlarmEvent:
    """Alarm generated by a device or by the watchdog."""

    source: str
    name: str
    severity: AlarmSeverity
    active: bool
    message: str
    timestamp: float
    evtype:AlarmEventType | None = None

    @property
    def identity(self) -> tuple[str, str]:
        return (self.source, self.name)