from enum import Enum, IntEnum, auto
from dataclasses import dataclass
from datetime import datetime

class AlarmSeverity(IntEnum):
    """Severity level of an alarm."""

    INFO = 10
    WARNING = 20
    ERROR = 30
    CRITICAL = 40

    def __str__(self) -> str:
        return self.name

class ComparisonOperator(Enum):
    LT = "<"
    LE = "<="
    EQ = "=="
    NE = "!="
    GE = ">="
    GT = ">"

    def __str__(self):
        return self.value

class AlarmCondition(Enum):
    VALUE = auto()
    INVALID = auto()

class InvalidValuePolicy(Enum):
    IGNORE = auto()
    ALARM = auto()

@dataclass 
class AlarmRule:
    """Base class for all alarm rules related devices measurements."""
    name: str
    var_name: str
    condition: AlarmCondition
    operator: ComparisonOperator|None
    threshold: float|None
    severity: AlarmSeverity
    enabled: bool = True
    invalid_policy: InvalidValuePolicy = InvalidValuePolicy.ALARM

    @classmethod
    def from_dict(cls, cfg: dict) -> "AlarmRule":

        required = (
            "name",
            "var_name",
            "condition",
            "severity",
        )

        for key in required:
            if key not in cfg:
                raise RuntimeError(
                    f"Missing alarm configuration key '{key}'."
                )
            #
        #
        
        condition = AlarmCondition[cfg.get("condition").upper()]

        if condition == AlarmCondition.INVALID:
            return cls(
                name=cfg["name"],
                var_name=cfg["var_name"],
                condition=condition,
                operator=None,
                threshold=None,
                severity=AlarmSeverity[cfg["severity"].upper()],
                enabled=cfg.get("enabled", True)
            )
        elif condition == AlarmCondition.VALUE:
            if "operator" not in cfg:
                raise RuntimeError(
                    "Missing alarm configuration key 'operator' "
                    "for VALUE alarm."
                )
            if "threshold" not in cfg:
                raise RuntimeError(
                    "Missing alarm configuration key 'threshold' "
                    "for VALUE alarm."
                )
            return cls(
                name=cfg["name"],
                var_name=cfg["var_name"],
                condition=condition,
                operator=ComparisonOperator(cfg["operator"]),
                threshold=float(cfg["threshold"]),
                severity=AlarmSeverity[cfg["severity"].upper()],
                enabled=cfg.get("enabled", True),
                invalid_policy=InvalidValuePolicy[cfg.get("invalid_policy", "ALARM").upper()]
            )

class AlarmEventType(Enum):
    ACTIVATED = auto()
    UPDATED = auto()
    SUPPRESSED = auto() #This tells the AlarmManager to remove the alarm without notification

@dataclass
class AlarmEvent:
    """Alarm generated by a device or by the watchdog."""

    source: str
    name: str
    severity: AlarmSeverity
    active: bool
    message: str
    timestamp: float
    evtype:AlarmEventType | None = None

    @property
    def identity(self) -> tuple[str, str]:
        return (self.source, self.name)